import Link from "next/link";
import { EntityCard } from "@/components/entity-card";
import { getRootEntities } from "@/lib/content";
import { sites } from "@/lib/sites";

const audiences = [
  ["For institutions", "Turn fragmented information into a shared picture of what is changing.", "See the coordination research", "/projects/civilization-coordination-crisis"],
  ["For operators", "Define the outcomes that matter, then make progress visible to everyone who depends on them.", "Explore outcome assurance", "/ideas/outcome-assurance"],
  ["For capital", "Find stronger signals about capability, execution, risk, and the transitions underneath performance.", "Follow economic transition", "/ideas/economic-state-transition"],
  ["For builders", "Help shape an open language for systems that need to work across organizational boundaries.", "Enter the protocol", "/projects/state-transition-protocol"],
];

const proofPoints = [
  ["01", "Make progress legible", "Translate activity into outcomes people can see, compare, and trust."],
  ["02", "Coordinate across boundaries", "Give independent teams a shared view without forcing them into one system."],
  ["03", "Compound what works", "Use verified transitions to direct attention, capital, and capability toward better next moves."],
];

export default async function Home() {
  const entities = await getRootEntities();
  return <main>
    <section className="campaign-hero"><div className="campaign-hero-inner shell"><div className="campaign-copy"><p className="eyebrow">Andrew Franklin Leo / Systems for economic civilization</p><h1>The future belongs to the people who can <em>coordinate</em> it.</h1><p className="campaign-lede">We are building the ideas, systems, and open protocols that turn intelligence into capability, capability into measurable outcomes, and outcomes into the next wave of progress.</p><div className="hero-actions"><Link className="button" href="#audiences">Find your entry point</Link><Link className="text-link" href="mailto:hello@andrewfranklinleo.com">Start a conversation</Link></div></div><div className="campaign-orbit" aria-label="The progression from intelligence to civilization"><div className="orbit-ring ring-one"><span>intelligence</span></div><div className="orbit-ring ring-two"><span>capability</span></div><div className="orbit-ring ring-three"><span>outcomes</span></div><div className="orbit-core">better<br /><em>coordination</em></div><p>THE WORK / 2026</p></div></div></section>
    <section className="signal-strip"><div className="shell signal-grid"><span>Intelligence</span><b>+</b><span>Capability</span><b>+</b><span>Verification</span><b>=</b><strong>Economic progress</strong></div></section>
    <section className="campaign-intro shell"><div><p className="eyebrow">The opportunity</p><h2 className="section-title">We have more capability than coordination.</h2></div><div className="campaign-intro-copy"><p>Important work is happening everywhere. But the people responsible for outcomes are still separated by incompatible systems, delayed feedback, and weak signals about what is actually changing.</p><p>The answer is not another dashboard. It is a better way to connect action, evidence, and value.</p><Link className="text-link" href="/projects/civilization-coordination-crisis">Why coordination is the constraint -&gt;</Link></div></section>
    <section className="audiences" id="audiences"><div className="shell"><div className="section-head"><div><p className="eyebrow">Who this is for</p><h2 className="section-title">Choose the<br /><em>problem you own.</em></h2></div><p>Different roles. One underlying question: how do we make meaningful change easier to see and easier to scale?</p></div><div className="audience-grid">{audiences.map(([label, description, action, href], index) => <Link className="audience-card" href={href} key={label}><span>0{index + 1}</span><p className="eyebrow">{label}</p><h3>{description}</h3><strong>{action} -&gt;</strong></Link>)}</div></div></section>
    <section className="proof shell"><div className="section-head"><div><p className="eyebrow">What we are building</p><h2 className="section-title">From activity<br />to <em>advantage.</em></h2></div><p>A practical body of work for people building institutions, companies, markets, and technologies that have to perform in the real world.</p></div><div className="proof-grid">{proofPoints.map(([number, title, body]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="feature-band"><div className="shell feature-grid"><div><p className="eyebrow">The flagship project</p><h2>State Transition<br /><em>Protocol.</em></h2><p>An open interoperability layer for independently operated realities. It helps organizations express what changed, why it matters, and what can be trusted without giving up sovereignty.</p><Link className="button" href="/projects/state-transition-protocol">Explore the protocol</Link></div><div className="feature-list"><div><span>For governments</span><strong>Coordinate public outcomes</strong></div><div><span>For enterprises</span><strong>Connect operations to consequence</strong></div><div><span>For AI systems</span><strong>Work from evidence, not confidence</strong></div><div><span>For capital</span><strong>See the transitions underneath risk</strong></div></div></div></section>
    <section className="projects shell"><div className="section-head"><div><p className="eyebrow">Projects in motion</p><h2 className="section-title">Ideas with<br /><em>somewhere to go.</em></h2></div><p>Research, protocols, and ventures connected to a larger theory of economic civilization.</p></div><div className="project-grid">{sites.map((site, index) => <Link className="project-link" href={`/projects/${site.slug}`} key={site.siteId}><span>0{index + 1} / {site.siteId}</span><h3>{site.name}</h3><p>{site.description}</p><strong>Open project -&gt;</strong></Link>)}</div></section>
    <section className="objects shell"><div className="section-head"><div><p className="eyebrow">The working archive</p><h2 className="section-title">See what is<br /><em>taking shape.</em></h2></div><p>Living ideas, models, systems, research, and ventures. Follow the work as it moves from question to implementation.</p></div><div className="object-grid">{entities.slice(0, 3).map((entity) => <EntityCard entity={entity} key={entity.entityId} />)}</div><Link className="text-link archive-link" href="/ideas">Browse the full working archive -&gt;</Link></section>
    <section className="closing shell"><p className="eyebrow">The invitation</p><h2>Build a future that can <em>coordinate itself.</em></h2><p>For the people building what comes next.</p><a className="button" href="mailto:hello@andrewfranklinleo.com">Start a dialogue -&gt;</a></section>
  </main>;
}
