import { EnterpriseTemplate } from './types';

export const ENTERPRISE_TEMPLATES: EnterpriseTemplate[] = [
  {
    id: 'tpl_manufacturing',
    vertical: 'manufacturing',
    name: 'Manufacturing AINE',
    description: 'AI-Native Enterprise for manufacturing: production planning, supply chain, quality, maintenance.',
    defaultAgentConfig: [
      { name: 'production-planner', type: 'execution', engine: 'wge', config: { focus: 'scheduling' }, required: true },
      { name: 'supply-chain-monitor', type: 'monitoring', engine: 'tower-control', config: { focus: 'vendor_health' }, required: true },
      { name: 'quality-inspector', type: 'execution', engine: 'eagl', config: { focus: 'defect_detection' }, required: true },
      { name: 'maintenance-predictor', type: 'intelligence', engine: 'tower-control', config: { focus: 'predictive_maintenance' }, required: false },
      { name: 'inventory-optimizer', type: 'execution', engine: 'wge', config: { focus: 'stock_levels' }, required: true },
      { name: 'compliance-monitor', type: 'governance', engine: 'eagl', config: { focus: 'manufacturing_compliance' }, required: true },
    ],
    defaultPolicies: ['production_safety', 'quality_standards', 'environmental_compliance', 'worker_safety'],
    requiredCapabilities: ['manufacturing', 'supply_chain', 'production_planning', 'quality_control'],
    estimatedMonthlyCost: 15000,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'tpl_healthcare',
    vertical: 'healthcare',
    name: 'Healthcare AINE',
    description: 'AI-Native Enterprise for healthcare: clinical safety, adverse events, drug interactions, HIPAA.',
    defaultAgentConfig: [
      { name: 'clinical-safety', type: 'governance', engine: 'eagl', config: { focus: 'patient_safety' }, required: true },
      { name: 'adverse-event-monitor', type: 'monitoring', engine: 'tower-control', config: { focus: 'adverse_events' }, required: true },
      { name: 'drug-interaction-checker', type: 'intelligence', engine: 'tower-control', config: { focus: 'pharmacology' }, required: true },
      { name: 'hipaa-compliance', type: 'governance', engine: 'eagl', config: { focus: 'hipaa' }, required: true },
      { name: 'patient-flow-optimizer', type: 'execution', engine: 'wge', config: { focus: 'scheduling' }, required: false },
      { name: 'clinical-documentation', type: 'execution', engine: 'wge', config: { focus: 'auto_docs' }, required: false },
    ],
    defaultPolicies: ['hipaa_compliance', 'clinical_safety', 'patient_privacy', 'adverse_event_reporting'],
    requiredCapabilities: ['healthcare', 'clinical_safety', 'hipaa', 'pharmacology'],
    estimatedMonthlyCost: 25000,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'tpl_finance',
    vertical: 'finance',
    name: 'Finance AINE',
    description: 'AI-Native Enterprise for financial services: fraud detection, KYC/AML, credit risk, regulatory reporting.',
    defaultAgentConfig: [
      { name: 'fraud-detector', type: 'intelligence', engine: 'tower-control', config: { focus: 'transaction_monitoring' }, required: true },
      { name: 'kyc-aml-agent', type: 'governance', engine: 'eagl', config: { focus: 'kyc_aml' }, required: true },
      { name: 'credit-risk-assessor', type: 'intelligence', engine: 'tower-control', config: { focus: 'credit_scoring' }, required: true },
      { name: 'regulatory-reporter', type: 'execution', engine: 'wge', config: { focus: 'regulatory_reporting' }, required: true },
      { name: 'market-risk-monitor', type: 'monitoring', engine: 'tower-control', config: { focus: 'market_risk' }, required: false },
      { name: 'compliance-officer', type: 'governance', engine: 'eagl', config: { focus: 'sox_mifid' }, required: true },
    ],
    defaultPolicies: ['sox_compliance', 'mifid_compliance', 'aml_screening', 'data_protection', 'conflict_of_interest'],
    requiredCapabilities: ['finance', 'fraud_detection', 'compliance', 'risk_management'],
    estimatedMonthlyCost: 30000,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'tpl_logistics',
    vertical: 'logistics',
    name: 'Logistics AINE',
    description: 'AI-Native Enterprise for logistics: fleet management, route optimization, fuel efficiency, driver scheduling.',
    defaultAgentConfig: [
      { name: 'route-optimizer', type: 'execution', engine: 'wge', config: { focus: 'route_planning' }, required: true },
      { name: 'fleet-monitor', type: 'monitoring', engine: 'tower-control', config: { focus: 'vehicle_health' }, required: true },
      { name: 'load-consolidator', type: 'execution', engine: 'wge', config: { focus: 'load_planning' }, required: true },
      { name: 'driver-scheduler', type: 'execution', engine: 'wge', config: { focus: 'scheduling' }, required: false },
      { name: 'fuel-optimizer', type: 'intelligence', engine: 'tower-control', config: { focus: 'fuel_efficiency' }, required: false },
      { name: 'compliance-tracker', type: 'governance', engine: 'eagl', config: { focus: 'transport_regulations' }, required: true },
    ],
    defaultPolicies: ['driver_hours_compliance', 'vehicle_safety', 'hazmat_regulations', 'environmental_standards'],
    requiredCapabilities: ['logistics', 'fleet_management', 'route_optimization'],
    estimatedMonthlyCost: 18000,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'tpl_professional_services',
    vertical: 'professional_services',
    name: 'Professional Services AINE',
    description: 'AI-Native Enterprise for professional services: realization rate, decision velocity, write-off reduction.',
    defaultAgentConfig: [
      { name: 'time-tracker', type: 'monitoring', engine: 'tower-control', config: { focus: 'billable_hours' }, required: true },
      { name: 'project-optimizer', type: 'execution', engine: 'wge', config: { focus: 'resource_allocation' }, required: true },
      { name: 'scope-monitor', type: 'monitoring', engine: 'tower-control', config: { focus: 'scope_creep' }, required: true },
      { name: 'billing-agent', type: 'execution', engine: 'wge', config: { focus: 'invoicing' }, required: true },
      { name: 'client-satisfaction', type: 'intelligence', engine: 'tower-control', config: { focus: 'nps_tracking' }, required: false },
      { name: 'knowledge-curator', type: 'intelligence', engine: 'tower-control', config: { focus: 'knowledge_management' }, required: false },
    ],
    defaultPolicies: ['client_confidentiality', 'conflict_checking', 'quality_standards', 'billing_accuracy'],
    requiredCapabilities: ['consulting', 'project_management', 'billing'],
    estimatedMonthlyCost: 12000,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'tpl_government',
    vertical: 'government',
    name: 'Government AINE',
    description: 'AI-Native Enterprise for government: infrastructure governance, transparency, corruption detection, citizen reporting.',
    defaultAgentConfig: [
      { name: 'transparency-agent', type: 'governance', engine: 'eagl', config: { focus: 'public_reporting' }, required: true },
      { name: 'budget-monitor', type: 'monitoring', engine: 'tower-control', config: { focus: 'budget_tracking' }, required: true },
      { name: 'procurement-auditor', type: 'governance', engine: 'eagl', config: { focus: 'procurement_integrity' }, required: true },
      { name: 'project-tracker', type: 'execution', engine: 'wge', config: { focus: 'infrastructure_projects' }, required: true },
      { name: 'citizen-reporter', type: 'execution', engine: 'wge', config: { focus: 'citizen_interface' }, required: false },
      { name: 'corruption-detector', type: 'intelligence', engine: 'tower-control', config: { focus: 'anomaly_detection' }, required: true },
    ],
    defaultPolicies: ['public_accountability', 'procurement_transparency', 'data_sovereignty', 'audit_requirements'],
    requiredCapabilities: ['government', 'public_sector', 'compliance', 'transparency'],
    estimatedMonthlyCost: 20000,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'tpl_general',
    vertical: 'general',
    name: 'General AINE',
    description: 'General-purpose AI-Native Enterprise with core agents for any industry.',
    defaultAgentConfig: [
      { name: 'operations-monitor', type: 'monitoring', engine: 'tower-control', config: {}, required: true },
      { name: 'task-executor', type: 'execution', engine: 'wge', config: {}, required: true },
      { name: 'compliance-agent', type: 'governance', engine: 'eagl', config: {}, required: true },
      { name: 'intelligence-gatherer', type: 'intelligence', engine: 'tower-control', config: {}, required: false },
    ],
    defaultPolicies: ['data_protection', 'operational_safety', 'audit_logging'],
    requiredCapabilities: [],
    estimatedMonthlyCost: 8000,
    createdAt: '2026-01-01T00:00:00Z',
  },
];
